TEST_REGISTRY = {
    "fppa_front_view": {
        "name": "FPPA Front View",
        "category": "isolated_measure",
        "description": "Analyse 2D de l'alignement hanche-genou-cheville en vue frontale.",
        "views": ["front"],
        "input_modes": ["video", "webcam"],
        "measures": ["left_fppa", "right_fppa"],
        "status": "implemented",
    },
    "squat_analysis": {
        "name": "Squat Analysis",
        "category": "functional_test",
        "description": "Analyse fonctionnelle du squat à partir de vues frontale et de profil.",
        "views": ["front", "side"],
        "input_modes": ["video", "webcam"],
        "measures": [
            "knee_flexion",
            "hip_flexion",
            "ankle_dorsiflexion",
            "trunk_inclination",
            "dynamic_knee_alignment",
            "symmetry",
            "depth",
        ],
        "status": "planned",
    },
    "single_leg_squat_analysis": {
        "name": "Single Leg Squat Analysis",
        "category": "functional_test",
        "description": "Analyse du contrôle moteur en appui unipodal.",
        "views": ["front", "side"],
        "input_modes": ["video", "webcam"],
        "measures": [
            "fppa",
            "pelvic_drop",
            "trunk_lean",
            "balance_control",
            "depth",
        ],
        "status": "planned",
    },
    "walking_analysis": {
        "name": "Walking Analysis",
        "category": "locomotion_test",
        "description": "Analyse de la marche à partir de vues de profil et arrière.",
        "views": ["side", "rear"],
        "input_modes": ["video"],
        "measures": [
            "cadence",
            "step_time",
            "joint_angles",
            "pelvic_drop",
            "step_width",
            "symmetry",
        ],
        "status": "planned",
    },
    "running_analysis": {
        "name": "Running Analysis",
        "category": "locomotion_test",
        "description": "Analyse de la course à partir de vues de profil et arrière.",
        "views": ["side", "rear"],
        "input_modes": ["video"],
        "measures": [
            "cadence",
            "stride_pattern",
            "foot_strike",
            "joint_angles",
            "pelvic_drop",
            "dynamic_knee_alignment",
            "symmetry",
        ],
        "status": "planned",
    },
}
